export {
  VerifiablApiError,
  type VerifiablAuth,
  VerifiablAuthError,
  VerifiablClient,
  type VerifiablClientOptions,
  type VerifiablEnvironment,
  type VerifiablErrorEvent,
  VerifiablIvReuseError,
  type VerifiablRequestEvent,
  type VerifiablRequestOptions,
  type VerifiablResponseEvent,
} from "./client.js";
export { type EncryptedPii, encryptPii } from "./crypto.js";
export {
  type AustralianV2IssuanceInput,
  type NewZealandV2IssuanceInput,
  type PreparedV2Payslip,
  prepareAustralianV2Payslip,
  prepareNewZealandV2Payslip,
} from "./issuance.js";
export {
  type BarcodeParts,
  buildBarcodePayload,
  buildScanUrl,
  DEFAULT_ISSUER_BASE_URL,
  DEFAULT_SCAN_BASE_URL,
  generateVerifiablReference,
  PDF_PAYLOAD_XMP_NAMESPACE,
  PDF_PAYLOAD_XMP_PROPERTY,
  SANDBOX_ISSUER_BASE_URL,
  SANDBOX_SCAN_BASE_URL,
  type ScanUrlOptions,
} from "./payload.js";
export {
  AUSTRALIAN_PAYSLIP_V2_SCHEMA,
  type AustralianPayslipV2,
  australianAllowanceTypes,
  australianDeductionTypes,
  australianEarningsTypes,
  australianEmploymentBases,
  australianEngagementTypes,
  australianOtherAllowanceCategories,
  australianPaidLeaveTypes,
  australianPayFrequencies,
  australianSalarySacrificeTypes,
  australianSuperContributionTypes,
  NEW_ZEALAND_PAYSLIP_V2_SCHEMA,
  type NewZealandPayslipV2,
  newZealandAllowanceTypes,
  newZealandDeductionTypes,
  newZealandEarningsTypes,
  newZealandLeaveBalanceUnits,
  newZealandPaidLeaveTypes,
  supportedV2Currencies,
} from "./payslipV2.js";
export {
  type AustralianAddress,
  type AustralianPiiFields,
  formatAustralianPii,
  formatNewZealandPii,
  formatPii,
  type NewZealandAddress,
  type NewZealandPiiFields,
  type PiiFieldName,
  type PiiFields,
  type PiiFieldViolation,
  type PiiFieldViolationReason,
  PiiValidationError,
  parsePii,
} from "./pii.js";

export {
  SUPPORTED_HORIZONTAL_PNG_PIXEL_WIDTHS,
  SUPPORTED_PNG_PIXEL_WIDTHS,
  type SupportedHorizontalPngPixelWidth,
  type SupportedPngPixelWidth,
} from "./qr/frame.js";
export {
  type BarcodePngOptions,
  type BarcodePngResult,
  createBarcodePng,
} from "./qr/png.js";
export {
  type BarcodeErrorCorrectionLevel,
  type BarcodeLayout,
  type BarcodeSvgOptions,
  type BarcodeSvgResult,
  createBarcodeSvg,
  QrCapacityError,
  type QrCapacityErrorDetail,
  type QrCapacityFailureReason,
} from "./qr/styled.js";

export {
  type BarcodeImage,
  type BatchRecordResult,
  type BatchRecordStatus,
  type EncryptionMetadata,
  IV_REUSED_CODE,
  isIvReuseResult,
  KNOWN_BATCH_RECORD_STATUSES,
  KNOWN_VERIFIABL_ERROR_CODES,
  type KnownBatchRecordStatus,
  type KnownSchemaRegisterNonPiiBatchRequest,
  type KnownVerifiablErrorCode,
  MAX_BATCH_RECORDS,
  type PayslipNonPii,
  type RegisterAndBuildBarcodeRequest,
  type RegisterAndBuildBarcodeResponse,
  type RegisterNonPiiBatchRequest,
  type RegisterNonPiiBatchResponse,
  type RegisterNonPiiRequest,
  type RegisterNonPiiResponse,
  supportedCurrencies,
  type VerifiablErrorBody,
  type VerifiablErrorCode,
  type VerifiablErrorDetail,
} from "./types.js";
